FROM nvidia/cuda:10.2-runtime

WORKDIR /app

ENV PATH="/root/miniconda3/bin:${PATH}"
#ENV CUDA_HOME='/usr/local/cuda-10.2'
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y \
	curl\
	git\
	libatlas-base-dev\
	libopenblas-dev\
	python3-dev\
	python3-pip\
	wget \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* 

# Install conda
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 

# Install MinkowskiEngine
# Skip if you already have pip installed on your python3
RUN curl https://bootstrap.pypa.io/get-pip.py | python3

# Get pip and install python requirements
RUN python3 -m pip install torch numpy
#RUN python3 -m pip install -U MinkowskiEngine --install-option="--blas=openblas" -v


RUN python3 -m pip install -U git+https://github.com/StanfordVL/MinkowskiEngine \
                           --install-option="--force_cuda" \
                           --install-option="--cuda_home=/usr/local/cuda-10.2" \ 
                           --install-option="--blas=openblas"

#RUN git clone https://github.com/NVIDIA/MinkowskiEngine.git
#RUN python MinkowskiEngine/setup.py install



# RUN conda create -n py3-mink python=3.7
# ENTRYPOINT ["bin/bash","conda activate py3-mink"]
# RUN conda install numpy mkl-include pytorch -c pytorch
# RUN conda install numpy mkl-include pytorch==1.5.0 torchvision==0.6.0 cudatoolkit=10.2 -c pytorch

# RUN git clone https://github.com/NVIDIA/MinkowskiEngine.git
# RUN cd MinkowskiEngine
# use openblas instead of mkl if things don't work
# RUN python MinkowskiEngine/setup.py install --blas=openblas








#RUN conda create -y -n py3-fcgf python=3.7     
#ENTRYPOINT ["bin/bash","conda activate -y py3-fcgf "]
#ENTRYPOINT ["bin/bash","conda install -y pytorch -c pytorch "]

#Run pip install git+https://github.com/NVIDIA/MinkowskiEngine.git@v0.5
#RUN apt-get install -y libopenblas-dev
#RUN pip install torch
#RUN pip install -U MinkowskiEngine --install-option="--blas=mkl" -v

#RUN apt-get update && apt-get install -y \
#	curl
